name: 'Docker Android Action'
description: 'Build your Android application using docker-android'
inputs:
  docker-android-tag:  # id of input
    description: 'The docker-android tag to use (https://hub.docker.com/repository/docker/fabernovel/android/tags)'
    required: false
    default: 'api-29-ndk-v1.0.0-alpha04'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.docker-android-tag }}
