name: Build test and deploy release images
on:
  release:
    types: [published]
jobs:
  build_and_test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        android_api: [28, 29]
        android_ndk: ["--android_ndk",""]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build test & deploy
        env:
          GIT_REF: ${{ github.ref }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: ./ci_cd.sh --build --test --deploy --android_api ${{ matrix.android_api }} ${{ matrix.android_ndk }} --test-lab
