name: Build test and deploy release images
on:
  push:
    tags:
      - v*
jobs:
  build_and_test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        android_api: [28, 29]
        android_ndk: ["--android_ndk",""]
    steps:
      - name: Checkout
        if: github.event.action == 'published'
        uses: actions/checkout@v1

      - name: Build test & deploy
        if: github.event.action == 'published'
        env:
          GIT_REF: ${{ github.ref }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: ./ci_cd.sh --build --test --deploy --android_api ${{ matrix.android_api }} ${{ matrix.android_ndk }}
