name: Build and test images
on:
  push:
    branches-ignore:
      - develop
      - master
jobs:
  build_and_test:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        android_api: [28, 29]
        android_ndk: ["--android_ndk",""]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Build
        run: ./ci_cd.sh --build --android_api ${{ matrix.android_api }} ${{ matrix.android_ndk }}

      - name: Test
        run: ./ci_cd.sh --test --android_api ${{ matrix.android_api }} ${{ matrix.android_ndk }}
