name: Build and test images
on:
  push:
    branches-ignore:
      - develop
      - master
      - 'release/**'
jobs:
  build_and_test:
    runs-on: [self-hosted, docker]
    container:
      image: docker://docker:stable-git
      options: --name=runner
    strategy:
      matrix:
        android_api: [28, 29]
        android_ndk: ["--android_ndk",""]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and test
        run: ./ci_cd.sh --build --test --android-api ${{ matrix.android_api }} ${{ matrix.android_ndk }}
