name: Test action
on:
  push:
    branches-ignore:
      - develop
      - master
      - 'release/**'
jobs:
  build_and_test:
    runs-on: ubuntu-18.04
    container:
      image: docker://docker:stable-git
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test action
        uses: ./action
        id: docker-android-action
        with:
          exec: echo "Hello world "
